name: OnlyAliveOnWood
version: ${project.version}
main: net.kunmc.lab.onlyaliveonwood.OnlyAliveOnWood
api-version: 1.16
authors: [chanmo7na]
commands:
  aliveonwood:
    description: OnlyAliveOnWood Main Command
    usage: /aliveonwood <start | stop>
    permission: op
